[package]
name = "personal_finance"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
enum-iterator = "0.7.0"

[dev-dependencies]
test-case = "1.2.0"

